//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.29 at 06:09:13 PM CEST 
//


package com.khronos.collada;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 			The scale element contains a mathematical vector that represents the relative proportions of the 
 * 			X, Y and Z axes of a coordinated system.
 * 			
 * 
 * <p>Java class for scale_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scale_type">
 *   &lt;simpleContent>
 *     &lt;restriction base="&lt;http://www.collada.org/2008/03/COLLADASchema>targetable_float3_type">
 *     &lt;/restriction>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scale_type")
public class ScaleType
    extends TargetableFloat3Type
{

    public void fuck(){System.out.println("fuuuuuuuck");}
}
